config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "reviews#index"
  resources :reviews, only: [:index,:create,:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, :image, :genre, :comment, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    Review.create(review_params)
    redirect_to root_path
  end

  private
  def review_params
    params.require(:review).permit(:title, :image, :genre, :comment).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/main/_header.html.haml
.header
  .header__main
    = link_to root_path do
      App-name
    = link_to new_review_path do
      .header__main__post
        Post
    .header__main__box
      .header__main__box__category
        Category
      .header__main__box__user
        User

app/views/main/_log-in.html.haml
.header
  .header__main
    App-name
.main_img
  .main_img__main
    .main_img__main__header
      .main_img__main__header__name
        ログイン
    .main_img__main__box
      .main_img__main__box__form-box
        .main_img__main__box__form-box__point
          名前
        %input.login-input-text{:name => "name", :placeholder => "", :type => "name", :value => ""}/

      .main_img__main__box__form-box
        .main_img__main__box__form-box__point
          パスワード
        %input.login-input-text{:name => "password", :placeholder => "", :type => "password", :value => ""}/

      .main_img__main__box__send-log
        %input.main_img__main__box__send__btn{:name => "create", :placeholder => "", :type => "submit", :value => "ログイン"}/

app/views/main/_user.html.haml
.header
  .header__main
    App-name
.main_img
  .main_img__main
    .main_img__main__header
      .main_img__main__header__name
        Sing up
      .main_img__main__box
        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            名前
          %input.login-input-text{:name => "name", :placeholder => "", :type => "name", :value => ""}/

        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            アドレス
          %input.login-input-text{:name => "e-mail", :placeholder => "", :type => "e-mail", :value => ""}/

        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            パスワード
          %input.login-input-text{:name => "password", :placeholder => "", :type => "password", :value => ""}/

        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            再確認
          %input.login-input-text{:name => "re.password", :placeholder => "", :type => "password", :value => ""}/

        .main_img__main__box__name
          お気に入りの本
        
        .main_img__main__box__create
          .main_img__main__box__create__name
            .main_img__main__box__create__name__point
              タイトル
            %input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__image
            .main_img__main__box__create__image__box__point
              画像
            %input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
            
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              ジャンル
            %input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              コメント
            %input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/


        .main_img__main__box__create
          .main_img__main__box__create__name
            .main_img__main__box__create__name__point
              タイトル
            %input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__image
            .main_img__main__box__create__image__box__point
              画像
            %input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              ジャンル
            %input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              コメント
            %input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/
            

        .main_img__main__box__create
          .main_img__main__box__create__name
            .main_img__main__box__create__name__point
              タイトル
            %input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__image
            .main_img__main__box__create__image__box__point
              画像
            %input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              ジャンル
            %input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              コメント
            %input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/
        
        .main_img__main__box__send
          %input.main_img__main__box__send__btn{:name => "create", :placeholder => "", :type => "submit", :value => "Create Account"}/
          

app/views/mains/_header.html.haml
.header
  .header__main
    = link_to root_path do
      App-name
    = link_to new_review_path do
      .header__main__post
        Post
    .header__main__box
      .header__main__box__category
        Category
      = link_to new_user_session_path do
        .header__main__box__user
          ログイン

app/views/mains/_log-in.html.haml
.main_img
  .main_img__main
    .main_img__main__header
      .main_img__main__header__name
        ログイン
    .main_img__main__box
      .main_img__main__box__form-box
        .main_img__main__box__form-box__point
          名前
        %input.login-input-text{:name => "name", :placeholder => "", :type => "name", :value => ""}/

      .main_img__main__box__form-box
        .main_img__main__box__form-box__point
          パスワード
        %input.login-input-text{:name => "password", :placeholder => "", :type => "password", :value => ""}/

      .main_img__main__box__send-log
        %input.main_img__main__box__send__btn{:name => "create", :placeholder => "", :type => "submit", :value => "ログイン"}/

app/views/mains/_main.html.haml
- @reviews.each do |review|
  .main_img
    .main_img__main
      .main_img__main__header
        .main_img__main__header__name
          Reviews
      .main_img__main__box
        .main_img__main__box__content
          .main_img__main__box__content__name
            =review.title
          .main_img__main__box__content__image
            = image_tag "modules/images.jpeg",size:"312x400",class: "image__box"
            //= image_tag review.image,size:"312x400",class: "image__box" if review.image.present?
          .main_img__main__box__content__wriget
            .main_img__main__box__content__wriget__point
              ジャンル
            .main_img__main__box__content__wriget__comment
              =review.genre
          .main_img__main__box__content__wriget
            .main_img__main__box__content__wriget__point
              コメント
            .main_img__main__box__content__wriget__comment
              =review.comment
            
          .main_img__main__box__content__user
            Hiroto


        .main_img__main__box__content
          .main_img__main__box__content__name
            ワンピース
          .main_img__main__box__content__image
            = image_tag "modules/one.jpeg",size:"312x400",class: "image__box"
            //= image_tag review.image,size:"312x400",class: "image__box" if review.image.present?
          .main_img__main__box__content__wriget
            .main_img__main__box__content__wriget__point
              ジャンル
            .main_img__main__box__content__wriget__comment
              少年漫画・海賊
          .main_img__main__box__content__wriget
            .main_img__main__box__content__wriget__point
              コメント
            .main_img__main__box__content__wriget__comment
              １度は読んだ方が良い
            
          .main_img__main__box__content__user
            Hiroto

        .main_img__main__box__content
          .main_img__main__box__content__name
            ドラゴンボール
          .main_img__main__box__content__image
            = image_tag "modules/doragonn.jpeg",size:"312x400",class: "image__box"
            //= image_tag review.image,size:"312x400",class: "image__box" if review.image.present?
          .main_img__main__box__content__wriget
            .main_img__main__box__content__wriget__point
              ジャンル
            .main_img__main__box__content__wriget__comment
              少年漫画・冒険
          .main_img__main__box__content__wriget
            .main_img__main__box__content__wriget__point
              コメント
            .main_img__main__box__content__wriget__comment
              １度は読んだ方が良い
            
          .main_img__main__box__content__user
            Hiroto

app/views/mains/_post.html.haml
= form_for [@review] do |f|
  .main_img
    .main_img__main
      .main_img__main__header
        .main_img__main__header__name
          投稿
        .main_img__main__box
          .main_img__main__box__create
            .main_img__main__box__create__name
              .main_img__main__box__create__name__point
                タイトル
              
              = f.text_field :title, class: 'login-input-title', placeholder: ''
              //%input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
            .main_img__main__box__create__image
              .main_img__main__box__create__image__box__point
                画像
              //= form_for [@review] do |f|
              = f.file_field :image, class: 'main_img__main__box__create__image__box', placeholder: ''
              //%input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
              
            .main_img__main__box__create__wriget
              .main_img__main__box__create__wriget__point
                ジャンル
              //= form_for [@review] do |f|
              = f.text_field :genre, class: 'login-input-wriget', placeholder: ''
              //%input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
            .main_img__main__box__create__wriget
              .main_img__main__box__create__wriget__point
                コメント
              //= form_for [@review] do |f|
              = f.text_field :comment, class: 'login-input-wriget', placeholder: ''
              //%input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__send
            //= form_for [@review] do |f|
            = f.submit "Create", class: "main_img__main__box__send__btn"
            //%input.main_img__main__box__send__btn{:name => "create", :placeholder => "", :type => "submit", :value => "Create Account"}/

app/views/mains/_user.html.haml
.main_img
  .main_img__main
    .main_img__main__header
      .main_img__main__header__name
        Sing up
      .main_img__main__box
        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            名前
          %input.login-input-text{:name => "name", :placeholder => "", :type => "name", :value => ""}/

        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            アドレス
          %input.login-input-text{:name => "e-mail", :placeholder => "", :type => "e-mail", :value => ""}/

        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            パスワード
          %input.login-input-text{:name => "password", :placeholder => "", :type => "password", :value => ""}/

        .main_img__main__box__form-box
          .main_img__main__box__form-box__point
            再確認
          %input.login-input-text{:name => "re.password", :placeholder => "", :type => "password", :value => ""}/

        .main_img__main__box__name
          お気に入りの本
        
        .main_img__main__box__create
          .main_img__main__box__create__name
            .main_img__main__box__create__name__point
              タイトル
            %input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__image
            .main_img__main__box__create__image__box__point
              画像
            %input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
            
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              ジャンル
            %input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              コメント
            %input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/


        .main_img__main__box__create
          .main_img__main__box__create__name
            .main_img__main__box__create__name__point
              タイトル
            %input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__image
            .main_img__main__box__create__image__box__point
              画像
            %input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              ジャンル
            %input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              コメント
            %input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/
            

        .main_img__main__box__create
          .main_img__main__box__create__name
            .main_img__main__box__create__name__point
              タイトル
            %input.login-input-title{:name => "title", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__image
            .main_img__main__box__create__image__box__point
              画像
            %input.main_img__main__box__create__image__box{:name => "image", :placeholder => "", :type => "file", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              ジャンル
            %input.login-input-wriget{:name => "genre", :placeholder => "", :type => "name", :value => ""}/
          .main_img__main__box__create__wriget
            .main_img__main__box__create__wriget__point
              コメント
            %input.login-input-wriget{:name => "comment", :placeholder => "", :type => "name", :value => ""}/
        
        .main_img__main__box__send
          //=link_to view_review_path do
          %input.main_img__main__box__send__btn{:name => "create", :placeholder => "", :type => "submit", :value => "アカウントを作成"}/
          

app/views/reviews/index.html.haml
.wrapper
  = render "mains/header"
  //= render "mains/main"
  //= render "post"
  = render "mains/user"
  //= render "log-in"
    

app/views/reviews/new.html.haml
.wrapper
  = render "main/header"
  = render "main/post"

app/views/reviews/view.html.haml
.wrapper
  = render "mains/header"
  = render "mains/main"